name: assert

on: push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          FILTER_REGEX_INCLUDE: .*\.sh|.editorconfig|.*\.java|.*\.kotlin|.*\.gradle
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BASH: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_GROOVY: true
          VALIDATE_JAVA: true
          VALIDATE_KOTLIN: true
  assemble_sample-java:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Assemble outputs
        run: ./gradlew sample-java:assemble
  assemble_sample-kotlin:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Assemble outputs
        run: ./gradlew sample-java:assemble
  androidTest_sample-java:
    runs-on: macos-10.15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew sample-java:connectedAndroidTest
  androidTest_sample-kotlin:
    runs-on: macos-10.15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew sample-kotlin:connectedAndroidTest
